#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: /log
#  file: /log/examonline.log
#  level:
#    com.zhk.examonline.LoggerTest: debug
spring:
  redis:
    host: 123.57.252.57
    password: examonline
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&&allowMultiQueries=true
    username: root
    password: 19971206zhk
